import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "./_components/Header";
import "./globals.css";

const montserrat = Montserrat({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
