import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "./_components/Header";
import "./globals.css";
import Footer from "./_components/Footer";

const montserrat = Montserrat({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased h-screen flex flex-col`}
      >
        <Header />
        <main className="grow container mx-auto py-5">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
