create table public.guest (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "fullName" text null,
  email text null,
  nationality text null,
  "countryFlag" text null,
  constraint guest_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."guest" ("id", "created_at", "fullName", "email", "nationality", "countryFlag") VALUES ('3', '2025-07-26 22:47:37.123509+00', 'Craig McLellen', 'cmclellen@gmail.com', 'South Africa', 'https://flagcdn.com/za.svg');